# workflow 이름
name: Hello Actions

# 실행 시점
on: 
  # push 이벤트 발생 시 실행
  push:
    # 어떤 브랜치에 push될 때 실행할지 지정
    # branches:
    #   - main
    branches: [main]
    # paths: (path-ignaore와 함께 쓸 수 없음.)
      # - 'src/**' # src 폴더 안의 모든 파일이 변경될 때 실행
      # - 'docs/**' # docs 폴더 안의 모든 파일이 변경될 때 실행
    # paths-ignore:
      # - 'README.md' # README.md 파일이 변경될 때는 실행하지 않음

# 이 workflow가 가진 잡들의 목록
jobs:
  # 잡의 이름(식별자)
  greet:
    # 러너 종류(어디서 실행할지)
    runs-on: ubuntu-latest
    # 잡 안에서 차례로 실행할 단계의 목록
    steps:
      # 단계의 이름(name: 화면에 보일 이름, run: 실제 실행할 명령어)
      - name: 인사하기
        run: echo "Hello, Actions! TaskFlow의 첫 워크 플로우입니다."
      - name: 러너 정보 보기
        run: |
          echo "러너 OS: $RUNNER_OS"
          uname -a